# Generated by Django 4.2 on 2023-05-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automailer', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
