# Generated by Django 3.2.18 on 2023-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automailer', '0004_rename_date_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default=44, max_length=5),
            preserve_default=False,
        ),
    ]
